### ISSUE TITLE
Error in astra package with data shape

### ISSUE THREAD

**Issue by CirilBohak** [harshit-gupta-epfl/CryoGAN#3]
I am trying to run CryoGAN to reproduce results published in your paper.

I encountered a problem. We successfully set up the conda environment, but when we try running the code with any of the supplied configuration files, we encounter a problem.

After fixing several misslinked paths I finally managed to get it running but after the training process starts I get the error below. I did set up the environment with the same packages, but also tried other versions of astra toolbox.

By running this command:
```console
python main_Clean.py Configs/train_Betagal.cfg
```

I get this error:
```console
...
Starting the training process ...
Lr decreases every 1.0 epochs
starting Training
Gaussian Blurring everything with sigma 2.0
Varphigenerator data size 101
Traceback (most recent call last):
  File "main_Clean.py", line 51, in <module>
    pro_gan.train(dataset=dataset, num_workers=1)
  File "/home/bohakc/cryogan/CryoGAN-Feng/CryoGAN_Clean.py", line 119, in train
    dis_lossIter, wass_lossIter, real_samples = self.optimize_discriminator(images)
  File "/home/bohakc/cryogan/CryoGAN-Feng/CryoGAN_Clean.py", line 261, in optimize_discriminator
    fake_samples, _, _, _, _ = self.gen(real_samples, GaussianSigma=self.args.GaussianSigma, ratio=self.ratio)
  File "/home/bohakc/cryogan/cryoem-env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/bohakc/cryogan/CryoGAN-Feng/Networks_Clean.py", line 39, in forward
    ratio=ratio)
  File "/home/bohakc/cryogan/cryoem-env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/bohakc/cryogan/CryoGAN-Feng/Generators_Clean.py", line 46, in forward
    proj, projClean = self.Projection(X, self.CurrentAngles)
  File "/home/bohakc/cryogan/CryoGAN-Feng/Generators_Clean.py", line 82, in Projection
    proj = Projection(X[0], self.args.RawProjectionSize, vectors.cpu())
  File "/home/bohakc/cryogan/CryoGAN-Feng/Functions/FunctionsGenerator.py", line 40, in Projection
    proj = Project.apply(X, RawProjectionSize, vectors)
  File "/home/bohakc/cryogan/CryoGAN-Feng/Functions/FunctionsGenerator.py", line 305, in forward
    vol_id = astra.data3d.link('-vol', vol_geom, vol_link)
  File "/home/bohakc/cryogan/cryoem-env/lib/python3.6/site-packages/astra/data3d.py", line 64, in link
    return d.create(datatype,geometry,data,True)
  File "astra/data3d_c.pyx", line 94, in astra.data3d_c.create
ValueError: The dimensions of the data do not match those specified in the geometry: (2, 384, 192) != (2, 192, 384)
```

Do you have any idea what to do to fix this?

**Comment by faisalbi** [comment]
Hey [CirilBohak](https://github.com/CirilBohak) have you been able to reproduce the results?
